adding if to skip checks

diff --git a/juno b/juno
--- a/juno
+++ b/juno
@@ -17,40 +17,47 @@ echo -n "Do you want to proceed further[Y/n]?: ";
 read input;
 if [ $input == 'Y' ]; 
 then
-	echo -n "I'm proceeding further! and ";
-  sleep 1s;
+	echo "I'm proceeding further! ";
+  echo "";
 else
 	echo -e "I'm $red quitting $white now!";
   exit 1;
 fi
 
-#check if required commands are there
-echo "Checking if required commands are in the system!.........";
-echo "";
-sleep 2s;
+if [ "$1" != "--skip-checks" ];
+then
+	{
+	#check if required commands are there
+	echo "Checking if required commands are in the system!.........";
+	echo "";
+	sleep 2s;
 
-commands=("date" "ifconfig" "lsof" "ps" "netstat" "w" "find" "less");
-for com in ${commands[@]};
-do
-	which $com &> /dev/null;
-	if [ $(echo $?) -eq 0 ];
-	then
-		if [ "$1" == "-v" ];
+	commands=("date" "ifconfig" "lsof" "ps" "netstat" "w" "find" "less");
+	for com in ${commands[@]};
+	do
+		which $com &> /dev/null;
+		if [ $(echo $?) -eq 0 ];
 		then
-			echo -e "$green pass! $megenda $com $white command available";
-    fi
-		sleep 1s;
-	else
-		echo -e "$red $com $white command not available, please install it";
-		echo "I'll not run further until all commands available in this system bye!!";
-		echo "";
-		exit 1;
-	fi
-done
+			if [ "$1" == "-v" ];
+			then
+				echo -e "$green pass! $megenda $com $white command available";
+    	fi
+			sleep 1s;
+		else
+			echo -e "$red $com $white command not available, please install it";
+			echo "I'll not run further until all commands available in this system bye!!";
+			echo "";
+			exit 1;
+		fi
+	done
 
-echo -e "$green Pass! $white all required commands are available in $(hostname)";
-sleep 1s;
-echo "";
-
+	echo -e "$green Pass! $white all required commands are available in $(hostname)";
+	sleep 1s;
+	echo "";
+}
+fi
 #operations
-get_time_zone;
+for operations in get_time_zone;
+do
+	$operations;
+done
